In [1]:
import pandas as pd
import string

In [2]:
df_train = pd.read_csv("drugsComTrain_raw.csv", parse_dates=["date"])
df_test = pd.read_csv("drugsComTest_raw.csv", parse_dates=["date"])

In [3]:
df_all = pd.concat([df_train,df_test])

In [4]:
condition_dn = df_all.groupby(['condition'])['drugName'].nunique().sort_values(ascending=False)

In [5]:
df_train = df_train.dropna(axis=0)
df_test = df_test.dropna(axis=0)

In [6]:
df_all = pd.concat([df_train,df_test]).reset_index()
del df_all['index']


In [7]:
all_list = set(df_all.index)
span_list = []
for i,j in enumerate(df_all['condition']):
    if '</span>' in j:
        span_list.append(i)

In [8]:
new_idx = all_list.difference(set(span_list))
df_all = df_all.iloc[list(new_idx)].reset_index()
del df_all['index']

In [9]:
df_condition = df_all.groupby(['condition'])['drugName'].nunique().sort_values(ascending=False)
df_condition = pd.DataFrame(df_condition).reset_index()

In [10]:
df_condition_1 = df_condition[df_condition['drugName']==1].reset_index()


In [11]:
all_list = set(df_all.index)
condition_list = []
for i,j in enumerate(df_all['condition']):
    for c in list(df_condition_1['condition']):
        if j == c:
            condition_list.append(i)
            
new_idx = all_list.difference(set(condition_list))
df_all = df_all.iloc[list(new_idx)].reset_index()
del df_all['index']

In [12]:
from bs4 import BeautifulSoup
import nltk
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [13]:
stops = set(stopwords.words('english'))

In [14]:
not_stop = ["aren't","couldn't","didn't","doesn't","don't","hadn't","hasn't","haven't","isn't","mightn't","mustn't","needn't","no","nor","not","shan't","shouldn't","wasn't","weren't","wouldn't"]
for i in not_stop:
    stops.remove(i)

In [15]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.


In [16]:
from sklearn import model_selection, preprocessing, metrics, ensemble, naive_bayes, linear_model
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import TruncatedSVD
import lightgbm as lgb

pd.options.mode.chained_assignment = None
pd.options.display.max_columns = 999
from bs4 import BeautifulSoup
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn import metrics

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, CuDNNGRU, Conv1D
from keras.layers import Bidirectional, GlobalMaxPool1D
from keras.models import Model
from keras import initializers, regularizers, constraints, optimizers, layers

Using TensorFlow backend.


In [17]:
stemmer = SnowballStemmer('english')

def review_to_words(raw_review):
    # 1. Delete HTML 
    review_text = BeautifulSoup(raw_review, 'html.parser').get_text()
    # 2. Make a space
    letters_only = re.sub('[^a-zA-Z]', ' ', review_text)
    # 3. lower letters
    words = letters_only.lower().split()
    # 5. Stopwords 
    meaningful_words = [w for w in words if not w in stops]
    # 6. Stemming
    stemming_words = [stemmer.stem(w) for w in meaningful_words]
    # 7. space join words
    return( ' '.join(stemming_words))


In [18]:
%time df_all['review_clean'] = df_all['review'].apply(review_to_words)

Wall time: 3min 3s


In [19]:
df_all['sentiment'] = df_all["rating"].apply(lambda x: 1 if x > 5 else 0)


In [20]:
df_train, df_test = train_test_split(df_all, test_size=0.33, random_state=42) 


In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

vectorizer = CountVectorizer(analyzer = 'word', 
                             tokenizer = None,
                             preprocessor = None, 
                             stop_words = None, 
                             min_df = 2, 
                             ngram_range=(4, 4),
                             max_features = 20000
                            )

In [22]:
pipeline = Pipeline([
    ('vect', vectorizer),
])

In [23]:
%time train_data_features = pipeline.fit_transform(df_train['review_clean'])
%time test_data_features = pipeline.fit_transform(df_test['review_clean'])


Wall time: 23.8 s
Wall time: 13.1 s


In [24]:
#Source code in keras 김태영'blog
# 0. Package
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
import random

# 1. Dataset
y_train = df_train['sentiment']
y_test = df_test['sentiment']
solution = y_test.copy()

# 2. Model Structure
model = keras.models.Sequential()

model.add(keras.layers.Dense(200, input_shape=(20000,)))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(300))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 3. Model compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 200)               4000200   
_________________________________________________________________
batch_normalization_1 (Batch (None, 200)               800       
_________________________________________________________________
activation_1 (Activation)    (None, 200)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 300)               60300     
_________________________________________________________________
batch_normalization_2 (Batch (None, 300)               1200      
_________________________________________________________________
activation_2 (Activation)    (None, 300)              

In [26]:
hist = model.fit(train_data_features, y_train, epochs=10, batch_size=64)


Epoch 1/10
142075/142075 [==============================] - 145s 1ms/step - loss: 0.5797 - accuracy: 0.7149
Epoch 2/10
142075/142075 [==============================] - 146s 1ms/step - loss: 0.4974 - accuracy: 0.7597
Epoch 3/10
142075/142075 [==============================] - 146s 1ms/step - loss: 0.4622 - accuracy: 0.7752
Epoch 4/10
142075/142075 [==============================] - 146s 1ms/step - loss: 0.4418 - accuracy: 0.7844
Epoch 5/10
142075/142075 [==============================] - 146s 1ms/step - loss: 0.4280 - accuracy: 0.7902
Epoch 6/10
142075/142075 [==============================] - 145s 1ms/step - loss: 0.4182 - accuracy: 0.7948
Epoch 7/10
142075/142075 [==============================] - 145s 1ms/step - loss: 0.4115 - accuracy: 0.7978
Epoch 8/10
142075/142075 [==============================] - 149s 1ms/step - loss: 0.4057 - accuracy: 0.7997
Epoch 9/10
142075/142075 [==============================] - 148s 1ms/step - loss: 0.4013 - accuracy: 0.8020
Epoch 10/10
142075/142075 [=

In [27]:
loss_and_metrics = model.evaluate(test_data_features, y_test, batch_size=32)
print('loss_and_metrics : ' + str(loss_and_metrics))

69978/69978 [==============================] - 20s 282us/step
loss_and_metrics : [1.0560347685687435, 0.648789644241333]


In [28]:
sub_preds_deep = model.predict(test_data_features,batch_size=32)

In [29]:
from sklearn.metrics import roc_auc_score, precision_recall_curve, roc_curve, average_precision_score
from sklearn.model_selection import KFold
from lightgbm import LGBMClassifier
from sklearn.metrics import confusion_matrix

#folds = KFold(n_splits=5, shuffle=True, random_state=546789)
target = df_train['sentiment']
feats = ['usefulCount']

sub_preds = np.zeros(df_test.shape[0])

trn_x, val_x, trn_y, val_y = train_test_split(df_train[feats], target, test_size=0.2, random_state=42) 
feature_importance_df = pd.DataFrame() 
    
clf = LGBMClassifier(
        n_estimators=2000,
        learning_rate=0.05,
        num_leaves=30,
        #colsample_bytree=.9,
        subsample=.9,
        max_depth=7,
        reg_alpha=.1,
        reg_lambda=.1,
        min_split_gain=.01,
        min_child_weight=2,
        silent=-1,
        verbose=-1,
        )
        
clf.fit(trn_x, trn_y, 
        eval_set= [(trn_x, trn_y), (val_x, val_y)], 
        verbose=100, early_stopping_rounds=100  #30
    )

sub_preds = clf.predict(df_test[feats])
        
fold_importance_df = pd.DataFrame()
fold_importance_df["feature"] = feats
fold_importance_df["importance"] = clf.feature_importances_
feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)

Training until validation scores don't improve for 100 rounds
[100]	training's binary_logloss: 0.570406	valid_1's binary_logloss: 0.572234
[200]	training's binary_logloss: 0.570206	valid_1's binary_logloss: 0.572221
Early stopping, best iteration is:
[168]	training's binary_logloss: 0.570241	valid_1's binary_logloss: 0.572209


In [30]:
solution = df_test['sentiment']
confusion_matrix(y_pred=sub_preds, y_true=solution)

array([[    0, 21009],
       [    0, 48969]], dtype=int64)

In [31]:
len_train = df_train.shape[0]
df_all = pd.concat([df_train,df_test])



In [32]:
df_all['date'] = pd.to_datetime(df_all['date'])
df_all['day'] = df_all['date'].dt.day
df_all['year'] = df_all['date'].dt.year
df_all['month'] = df_all['date'].dt.month

Note: you may need to restart the kernel to use updated packages.


In [34]:
from textblob import TextBlob
from tqdm import tqdm
reviews = df_all['review_clean']

Predict_Sentiment = []
for review in tqdm(reviews):
    blob = TextBlob(review)
    Predict_Sentiment += [blob.sentiment.polarity]
df_all["Predict_Sentiment"] = Predict_Sentiment
df_all.head()

100%|████████████████████████████████████████████████████████████████████████| 212053/212053 [01:18<00:00, 2688.69it/s]


uniqueID      drugName                    condition  \
130185     66913      Seroquel  Generalized Anxiety Disorde   
155501    222222   Fluconazole       Onychomycosis, Toenail   
75325      75807     Temazepam                     Insomnia   
19174     229747      Ketamine                         Pain   
209735    102495  Aripiprazole     Major Depressive Disorde   

                                                   review  rating       date  \
130185  "After trying nearly every SSRI on the market ...       9 2010-11-26   
155501  "This takes 6+ months, but did clear up a deca...       9 2008-05-03   
75325   "Worked for awhile pretty well but then went b...       2 2016-04-21   
19174   "I was given this after surgery for pain as I ...       1 2016-04-16   
209735  "Abilify served me well over a two month perio...       9 2016-12-16   

        usefulCount                                       review_clean  \
130185          102  tri near everi ssri market place pristiq impro...   
155501           39                 take month clear decad long infect   
75325            15  work awhil pretti well went back mayb get hour...   
19174            19  given surgeri pain morphin tri drug sort omg w...   
209735            5  abilifi serv well two month period antidepress...   

        sentiment  day  year  month  Predict_Sentiment  
130185          1   26  2010     11           0.023958  
155501          1    3  2008      5           0.025000  
75325           0   21  2016      4          -0.125000  
19174           0   16  2016      4           0.166667  
209735          1   16  2016     12           0.038889

In [35]:
np.corrcoef(df_all["Predict_Sentiment"], df_all["rating"])

array([[1.        , 0.25709864],
       [0.25709864, 1.        ]])

In [36]:
np.corrcoef(df_all["Predict_Sentiment"], df_all["sentiment"])

array([[1.        , 0.23518272],
       [0.23518272, 1.        ]])

In [37]:
reviews = df_all['review']

Predict_Sentiment = []
for review in tqdm(reviews):
    blob = TextBlob(review)
    Predict_Sentiment += [blob.sentiment.polarity]
df_all["Predict_Sentiment2"] = Predict_Sentiment

100%|████████████████████████████████████████████████████████████████████████| 212053/212053 [02:37<00:00, 1343.57it/s]


In [38]:
np.corrcoef(df_all["Predict_Sentiment2"], df_all["rating"])
np.corrcoef(df_all["Predict_Sentiment2"], df_all["sentiment"])

array([[1.        , 0.31714515],
       [0.31714515, 1.        ]])

In [39]:
df_all['count_sent']=df_all["review"].apply(lambda x: len(re.findall("\n",str(x)))+1)

#Word count in each comment:(단어갯수)
df_all['count_word']=df_all["review_clean"].apply(lambda x: len(str(x).split()))

#Unique word count(unique한 단어 갯수)
df_all['count_unique_word']=df_all["review_clean"].apply(lambda x: len(set(str(x).split())))

#Letter count(리뷰길이)
df_all['count_letters']=df_all["review_clean"].apply(lambda x: len(str(x)))

#punctuation count(특수문자)
df_all["count_punctuations"] = df_all["review"].apply(lambda x: len([c for c in str(x) if c in string.punctuation]))

#upper case words count(전부다 대문자인 단어 갯수)
df_all["count_words_upper"] = df_all["review"].apply(lambda x: len([w for w in str(x).split() if w.isupper()]))

#title case words count(첫글자가 대문자인 단어 갯수)
df_all["count_words_title"] = df_all["review"].apply(lambda x: len([w for w in str(x).split() if w.istitle()]))

#Number of stopwords(불용어 갯수)
df_all["count_stopwords"] = df_all["review"].apply(lambda x: len([w for w in str(x).lower().split() if w in stops]))

#Average length of the words(평균단어길이)
df_all["mean_word_len"] = df_all["review_clean"].apply(lambda x: np.mean([len(w) for w in str(x).split()]))

D:\programs\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)


In [40]:
df_all['season'] = df_all["month"].apply(lambda x: 1 if ((x>2) & (x<6)) else(2 if (x>5) & (x<9) else (3 if (x>8) & (x<12) else 4)))

In [41]:
confusion_matrix(y_pred=sub_preds, y_true=solution)

array([[    0, 21009],
       [    0, 48969]], dtype=int64)

In [42]:
cols = feature_importance_df[["feature", "importance"]].groupby("feature").mean().sort_values(
    by="importance", ascending=False)[:50].index

best_features = feature_importance_df.loc[feature_importance_df.feature.isin(cols)]


In [43]:
word_table = pd.read_csv("inquirerbasic.csv")

In [44]:
#Positiv word list   
temp_Positiv = []
Positiv_word_list = []
for i in range(0,len(word_table.Positiv)):
    if word_table.iloc[i,2] == "Positiv":
        temp = word_table.iloc[i,0].lower()
        temp1 = re.sub('\d+', '', temp)
        temp2 = re.sub('#', '', temp1) 
        temp_Positiv.append(temp2)

Positiv_word_list = list(set(temp_Positiv))
len(temp_Positiv)
len(Positiv_word_list)  #del temp_Positiv

#Negativ word list          
temp_Negativ = []
Negativ_word_list = []
for i in range(0,len(word_table.Negativ)):
    if word_table.iloc[i,3] == "Negativ":
        temp = word_table.iloc[i,0].lower()
        temp1 = re.sub('\d+', '', temp)
        temp2 = re.sub('#', '', temp1) 
        temp_Negativ.append(temp2)

Negativ_word_list = list(set(temp_Negativ))
len(temp_Negativ)
len(Negativ_word_list)

2006

In [45]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(vocabulary = Positiv_word_list)
content = df_test['review_clean']
X = vectorizer.fit_transform(content)
f = X.toarray()
f = pd.DataFrame(f)
f.columns=Positiv_word_list
df_test["num_Positiv_word"] = f.sum(axis=1)

vectorizer2 = CountVectorizer(vocabulary = Negativ_word_list)
content = df_test['review_clean']
X2 = vectorizer2.fit_transform(content)
f2 = X2.toarray()
f2 = pd.DataFrame(f2)
f2.columns=Negativ_word_list
df_test["num_Negativ_word"] = f2.sum(axis=1)

In [46]:
##3. decide sentiment
df_test["Positiv_ratio"] = df_test["num_Positiv_word"]/(df_test["num_Positiv_word"]+df_test["num_Negativ_word"])
df_test["sentiment_by_dic"] = df_test["Positiv_ratio"].apply(lambda x: 1 if (x>=0.5) else (0 if (x<0.5) else 0.5))

df_test.head()

uniqueID                          drugName  \
147354    126702                       Brimonidine   
195249     84765  Ethinyl estradiol / norgestimate   
86265      71559                           Vraylar   
44172     132320                            Ativan   
90569     177278                        Duloxetine   

                          condition  \
147354                      Rosacea   
195249                Birth Control   
86265               Bipolar Disorde   
44172                       Anxiety   
90569   Generalized Anxiety Disorde   

                                                   review  rating       date  \
147354  "Never , never , never use this cream !!!!!! I...       1 2015-08-31   
195249  "I was switched to this after about 9 months o...      10 2016-05-01   
86265   "I began at 1.5 then titrated to 3mg dosage. A...       3 2016-08-17   
44172   "Ativan 0.5mg calms me down considerably withi...       5 2012-01-12   
90569   "My thoughts on Cymbalta: Cymbalta has left me...       1 2017-05-03   

        usefulCount                                       review_clean  \
147354           17  never never never use cream help way angri dis...   
195249            3  switch month mononessa ask switch happen anywa...   
86265            17  began titrat mg dosag first love medicin compl...   
44172            26  ativan mg calm consider within minut side effe...   
90569            29  thought cymbalta cymbalta left fog no feel non...   

        sentiment  num_Positiv_word  num_Negativ_word  Positiv_ratio  \
147354          0               NaN               NaN            NaN   
195249          1               NaN               NaN            NaN   
86265           0               NaN               NaN            NaN   
44172           0               0.0               4.0            0.0   
90569           0               NaN               NaN            NaN   

        sentiment_by_dic  
147354               0.5  
195249               0.5  
86265                0.5  
44172                0.0  
90569                0.5

In [47]:
def userful_count(data):
    grouped = data.groupby(['condition']).size().reset_index(name='user_size')
    data = pd.merge(data,grouped,on='condition',how='left')
    return data
#___________________________________________________________
df_test =  userful_count(df_test) 
df_test['usefulCount'] = df_test['usefulCount']/df_test['user_size']

In [48]:
df_test['deep_pred'] = sub_preds_deep
df_test['machine_pred'] = sub_preds

df_test['total_pred'] = (df_test['deep_pred'] + df_test['machine_pred'] + df_test['sentiment_by_dic'])*df_test['usefulCount']

In [49]:
df_test = df_test.groupby(['condition','drugName']).agg({'total_pred' : ['mean']})
df_test

total_pred
                                                       mean
condition                drugName                          
ADHD                     Adderall                  0.071786
                         Adderall XR               0.043242
                         Adzenys XR-ODT            0.012092
                         Amantadine                0.011008
                         Amphetamine               0.015865
...                                                     ...
moterol)                 Arformoterol              2.044659
                         Budesonide / formoterol   2.342874
von Willebrand's Disease Stimate                   7.013450
zen Shoulde              Nabumetone               27.773980
                         Naproxen                  1.448300

[5773 rows x 1 columns]